export const SCHEDULED_JOB_NAMES = {
  MONTHLY_CHARGES_GENERATOR: 'MONTHLY_CHARGES_GENERATOR',
  MONTHLY_INVOICE_GENERATOR: 'MONTHLY_INVOICE_GENERATOR',
  PAYMENT_REMINDER_JOB: 'PAYMENT_REMINDER_JOB',
  TRIAL_EXPIRATION_JOB: 'TRIAL_EXPIRATION_JOB',
  SUBSCRIPTION_BILLING_JOB: 'SUBSCRIPTION_BILLING_JOB',
  OVERDUE_SUBSCRIPTION_JOB: 'OVERDUE_SUBSCRIPTION_JOB',
  NOTIFICATION_DISPATCHER_JOB: 'NOTIFICATION_DISPATCHER_JOB',
  DEBT_REMINDER_JOB: 'DEBT_REMINDER_JOB',
  CLIENT_FOLLOW_UP_REMINDER_JOB: 'CLIENT_FOLLOW_UP_REMINDER_JOB',
} as const;

export type ScheduledJobName = (typeof SCHEDULED_JOB_NAMES)[keyof typeof SCHEDULED_JOB_NAMES];

export const ALL_SCHEDULED_JOB_NAMES: ScheduledJobName[] = Object.values(SCHEDULED_JOB_NAMES);

