services:
  - type: web
    name: espace-backend
    env: node
    branch: main
    rootDir: backend
    autoDeploy: true
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: PORT
        sync: false
      - key: CORS_ORIGIN
        sync: false
