ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'METERS';
ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'METER_READINGS';

ALTER TYPE "MeterType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TYPE "MeterReadingSource" ADD VALUE IF NOT EXISTS 'SYSTEM';
