ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'NONE';
ALTER TYPE "PaymentIntentStatus" ADD VALUE IF NOT EXISTS 'VIEWED';
ALTER TYPE "PaymentIntentStatus" ADD VALUE IF NOT EXISTS 'PAID_MANUALLY';
