import {
  LaunchChecklistCategory,
  LaunchChecklistSeverity,
  PlatformServiceBillingCycle,
  PlatformServiceCriticality,
  PlatformServiceStatus,
  PlatformServiceType,
} from '@prisma/client';

export const LAUNCH_CHECKLIST_SEEDS = [
  ['product_public_website', 'PRODUCT', 'Public website ready', 'Website public, CTA-uri si formulare publice pregatite.', 'CRITICAL', true, '/ro'],
  ['product_admin_dashboard', 'PRODUCT', 'Admin dashboard ready', 'Admin poate opera fluxurile principale.', 'CRITICAL', true, '/ro/admin'],
  ['product_resident_portal', 'PRODUCT', 'Resident portal ready', 'Portalul locatar este utilizabil pe mobil.', 'CRITICAL', true, '/ro/resident'],
  ['product_superadmin_crm', 'PRODUCT', 'Superadmin CRM ready', 'Superadmin poate gestiona APC-uri si cereri clienti.', 'CRITICAL', true, '/ro/superadmin'],
  ['product_help_center', 'PRODUCT', 'Help Center ready', 'Help Center si onboarding guide sunt disponibile.', 'WARNING', true, '/ro/help'],
  ['infra_frontend_hosting', 'INFRASTRUCTURE', 'Frontend hosting configured', 'Vercel sau hosting frontend configurat.', 'CRITICAL', true, null],
  ['infra_backend_hosting', 'INFRASTRUCTURE', 'Backend hosting configured', 'Render sau hosting backend configurat.', 'CRITICAL', true, null],
  ['infra_database', 'INFRASTRUCTURE', 'Database configured', 'Baza de date production configurata.', 'CRITICAL', true, null],
  ['infra_domain', 'INFRASTRUCTURE', 'Domain configured', 'Domeniul public este configurat.', 'CRITICAL', true, 'https://espace.md'],
  ['infra_https', 'INFRASTRUCTURE', 'HTTPS enabled', 'HTTPS este activ pe domeniile publice.', 'CRITICAL', true, null],
  ['db_migrations_applied', 'DATABASE', 'Prisma migrations applied', 'Migrations production sunt aplicate controlat.', 'CRITICAL', true, null],
  ['db_reachable', 'DATABASE', 'Production database reachable', 'Backend poate ajunge la baza de date.', 'CRITICAL', true, '/ro/superadmin/monitoring/health'],
  ['db_backup_strategy', 'DATABASE', 'Backup strategy documented', 'Strategia de backup este documentata.', 'WARNING', true, null],
  ['deploy_main_branch', 'DEPLOYMENT', 'GitHub main branch is production branch', 'Branch-ul main este branch-ul de productie.', 'CRITICAL', true, null],
  ['deploy_vercel_main', 'DEPLOYMENT', 'Vercel connected to main', 'Vercel este conectat la main.', 'CRITICAL', true, null],
  ['deploy_render_main', 'DEPLOYMENT', 'Render connected to main', 'Render este conectat la main.', 'CRITICAL', true, null],
  ['deploy_build_passes', 'DEPLOYMENT', 'Build passes', 'npm run build trece.', 'CRITICAL', true, null],
  ['deploy_last_success', 'DEPLOYMENT', 'Last deploy successful', 'Ultimul deploy este functional.', 'CRITICAL', true, null],
  ['env_database_url', 'ENVIRONMENT', 'DATABASE_URL present', 'DATABASE_URL este prezent in backend.', 'CRITICAL', true, '/ro/superadmin/launch/env'],
  ['env_jwt_secret', 'ENVIRONMENT', 'JWT_SECRET present', 'JWT_SECRET este prezent.', 'CRITICAL', true, '/ro/superadmin/launch/env'],
  ['env_cors_origin', 'ENVIRONMENT', 'CORS_ORIGIN present', 'CORS este configurat pentru productie.', 'CRITICAL', true, '/ro/superadmin/launch/env'],
  ['env_next_public_api_url', 'ENVIRONMENT', 'NEXT_PUBLIC_API_URL present', 'Frontend are URL API public.', 'CRITICAL', true, '/ro/superadmin/launch/env'],
  ['env_next_public_socket_url', 'ENVIRONMENT', 'NEXT_PUBLIC_SOCKET_URL present', 'Socket URL este verificat sau marcat optional.', 'WARNING', false, '/ro/superadmin/launch/env'],
  ['env_email_provider', 'ENVIRONMENT', 'EMAIL provider env checked', 'Providerul email este verificat sau fallback documentat.', 'WARNING', true, '/ro/superadmin/launch/env'],
  ['env_sms_provider', 'ENVIRONMENT', 'SMS provider env checked', 'Providerul SMS este verificat sau dezactivat controlat.', 'INFO', false, '/ro/superadmin/launch/env'],
  ['env_payment_provider', 'ENVIRONMENT', 'Payment provider env checked', 'Payment provider este placeholder si nu proceseaza bani.', 'WARNING', true, '/ro/superadmin/launch/env'],
  ['security_rbac', 'SECURITY', 'RBAC enabled', 'Roluri si permisiuni active.', 'CRITICAL', true, null],
  ['security_tenant_isolation', 'SECURITY', 'Tenant isolation checked', 'Accesul pe asociatie este verificat.', 'CRITICAL', true, null],
  ['security_support_audited', 'SECURITY', 'Superadmin support access audited', 'Support access este controlat si auditat.', 'WARNING', true, null],
  ['security_audit_log', 'SECURITY', 'Audit log enabled', 'Audit log este activ pentru actiuni sensibile.', 'CRITICAL', true, null],
  ['security_monitoring', 'SECURITY', 'Monitoring enabled', 'Monitoring si error tracking intern sunt active.', 'CRITICAL', true, '/ro/superadmin/monitoring'],
  ['legal_privacy', 'LEGAL', 'Privacy page published', 'Politica de confidentialitate este publicata.', 'CRITICAL', true, '/ro/confidentialitate'],
  ['legal_terms', 'LEGAL', 'Terms page published', 'Termenii sunt publicati.', 'CRITICAL', true, '/ro/termeni'],
  ['legal_cookies', 'LEGAL', 'Cookie page published', 'Politica cookies este publicata.', 'WARNING', true, '/ro/cookies'],
  ['legal_security', 'LEGAL', 'Security page published', 'Pagina securitate este publicata.', 'WARNING', true, '/ro/securitate'],
  ['legal_contact', 'LEGAL', 'Contact page working', 'Pagina contact si formularele functioneaza.', 'CRITICAL', true, '/ro/contact'],
  ['billing_internal_invoices', 'BILLING', 'Internal invoices working', 'Facturile interne sunt operationale.', 'CRITICAL', true, null],
  ['billing_manual_payments', 'BILLING', 'Manual payments working', 'Platile manuale sunt operationale.', 'CRITICAL', true, null],
  ['billing_saas_plans', 'BILLING', 'SaaS plans configured', 'Planurile SaaS sunt configurate.', 'WARNING', true, '/ro/superadmin/billing/plans'],
  ['billing_saas_subscription', 'BILLING', 'SaaS subscription configured', 'Abonamentul primei APC este configurat.', 'WARNING', true, null],
  ['billing_saas_invoice', 'BILLING', 'SaaS invoice skeleton working', 'Facturarea SaaS interna este disponibila.', 'WARNING', true, '/ro/superadmin/billing/saas-invoices'],
  ['notifications_in_app', 'NOTIFICATIONS', 'In-app notifications working', 'Notificarile in-app sunt disponibile.', 'WARNING', true, null],
  ['notifications_email', 'NOTIFICATIONS', 'Email provider configured or console fallback', 'Email real sau console fallback documentat.', 'WARNING', true, '/ro/superadmin/notifications/providers'],
  ['notifications_password_reset', 'NOTIFICATIONS', 'Password reset notification flow checked', 'Reset password verificat.', 'CRITICAL', true, null],
  ['notifications_invitations', 'NOTIFICATIONS', 'Invitations notification flow checked', 'Invitatiile resident/staff sunt verificate.', 'WARNING', true, null],
  ['payments_online_placeholder', 'PAYMENTS', 'Online payments disabled/placeholder clearly shown', 'Platile online sunt prezentate ca in pregatire.', 'CRITICAL', true, '/ro/superadmin/payments'],
  ['payments_intent_safe', 'PAYMENTS', 'Payment intent skeleton does not process real money', 'PaymentIntent nu proceseaza bani reali.', 'CRITICAL', true, '/ro/superadmin/payments/intents'],
  ['payments_manual_primary', 'PAYMENTS', 'Manual payments are primary payment method', 'Platile manuale raman metoda principala.', 'CRITICAL', true, '/ro/admin/payments'],
  ['first_apc_active', 'FIRST_APC', 'First association active', 'Prima APC este activa.', 'CRITICAL', true, '/ro/superadmin/associations'],
  ['first_apc_apartments', 'FIRST_APC', 'Apartments imported', 'Apartamentele sunt importate.', 'CRITICAL', true, null],
  ['first_apc_residents', 'FIRST_APC', 'Residents imported', 'Locatarii sunt importati.', 'CRITICAL', true, null],
  ['first_apc_tariffs', 'FIRST_APC', 'Tariffs configured', 'Tarifele sunt configurate.', 'CRITICAL', true, null],
  ['first_apc_meters', 'FIRST_APC', 'Meters configured, if needed', 'Contoarele sunt configurate sau marcate neaplicabil.', 'WARNING', false, null],
  ['first_apc_data_quality', 'FIRST_APC', 'Data quality checked', 'Data Quality a fost rulat.', 'WARNING', true, '/ro/admin/data-quality'],
  ['first_apc_billing_run', 'FIRST_APC', 'Billing run tested', 'Fluxul de facturare a fost testat.', 'CRITICAL', true, '/ro/admin/billing'],
  ['first_apc_resident_access', 'FIRST_APC', 'Resident access tested', 'Accesul locatarilor a fost testat.', 'WARNING', true, '/ro/admin/resident-access'],
  ['support_help_center', 'SUPPORT', 'Help Center available', 'Help Center este disponibil.', 'WARNING', true, '/ro/help'],
  ['support_admin_onboarding', 'SUPPORT', 'Admin onboarding guide available', 'Ghidul de onboarding Admin este disponibil.', 'WARNING', true, '/ro/admin/onboarding-guide'],
  ['support_process_defined', 'SUPPORT', 'Contact/support process defined', 'Procesul de suport este definit.', 'WARNING', true, null],
  ['monitoring_health', 'MONITORING', '/api/health works', 'Health endpoint raspunde.', 'CRITICAL', true, '/ro/superadmin/monitoring/health'],
  ['monitoring_readiness', 'MONITORING', 'readiness works', 'Readiness endpoint este verificat.', 'CRITICAL', true, '/ro/superadmin/monitoring/health'],
  ['monitoring_page', 'MONITORING', 'monitoring page works', 'Pagina Monitoring functioneaza.', 'CRITICAL', true, '/ro/superadmin/monitoring'],
  ['monitoring_error_boundary', 'MONITORING', 'error boundary works', 'Error boundary frontend este disponibil.', 'WARNING', true, null],
  ['costs_services_registered', 'COSTS', 'Critical services registered', 'Serviciile critice sunt inregistrate.', 'CRITICAL', true, '/ro/superadmin/launch/services'],
  ['costs_reviewed', 'COSTS', 'Monthly costs reviewed', 'Costurile lunare sunt revizuite.', 'WARNING', true, '/ro/superadmin/launch/costs'],
  ['costs_due_dates', 'COSTS', 'Payment due dates added', 'Datele de plata sunt completate.', 'WARNING', true, '/ro/superadmin/launch/costs'],
  ['costs_renewal_reminders', 'COSTS', 'Renewal reminders checked', 'Renewal reminders sunt verificate manual.', 'INFO', false, '/ro/superadmin/launch/costs'],
] as const satisfies ReadonlyArray<readonly [string, keyof typeof LaunchChecklistCategory, string, string, keyof typeof LaunchChecklistSeverity, boolean, string | null]>;

export const PLATFORM_SERVICE_SEEDS = [
  {
    name: 'GitHub',
    type: PlatformServiceType.SOURCE_CONTROL,
    providerName: 'GitHub',
    purpose: 'Cod sursa, repository, branch main, colaborare si istoric.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: [],
    impactIfDown: 'Nu poti face push/deploy nou, dar aplicatia live poate continua sa ruleze.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Vercel',
    type: PlatformServiceType.HOSTING_FRONTEND,
    providerName: 'Vercel',
    purpose: 'Hosting frontend Next.js.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: ['NEXT_PUBLIC_API_URL', 'NEXT_PUBLIC_SOCKET_URL'],
    impactIfDown: 'Frontendul public/Admin/Resident poate deveni indisponibil.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Render',
    type: PlatformServiceType.HOSTING_BACKEND,
    providerName: 'Render',
    purpose: 'Hosting backend NestJS API.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: ['DATABASE_URL', 'JWT_SECRET', 'CORS_ORIGIN', 'PORT'],
    impactIfDown: 'API-ul nu functioneaza, aplicatia nu poate incarca date.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Supabase',
    type: PlatformServiceType.DATABASE,
    providerName: 'Supabase',
    purpose: 'Baza de date PostgreSQL production.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.MONTHLY,
    environmentKeys: ['DATABASE_URL'],
    impactIfDown: 'Datele aplicatiei nu pot fi citite/scrise.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Cursor',
    type: PlatformServiceType.AI_CODING_TOOL,
    providerName: 'Cursor',
    purpose: 'Dezvoltare si modificari cod asistate AI.',
    criticality: PlatformServiceCriticality.IMPORTANT,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.MONTHLY,
    environmentKeys: [],
    impactIfDown: 'Dezvoltarea devine mai lenta, dar platforma live poate functiona.',
    isRequiredForLaunch: false,
  },
  {
    name: 'OpenAI / Codex',
    type: PlatformServiceType.AI_CODING_TOOL,
    providerName: 'OpenAI',
    purpose: 'Asistenta AI pentru implementare, prompts si analiza cod.',
    criticality: PlatformServiceCriticality.IMPORTANT,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.MONTHLY,
    environmentKeys: [],
    impactIfDown: 'Dezvoltarea si automatizarea sunt afectate, nu neaparat platforma live.',
    isRequiredForLaunch: false,
  },
  {
    name: 'Domain Registrar',
    type: PlatformServiceType.DOMAIN,
    providerName: 'Unknown',
    purpose: 'Domeniul public Espace.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.YEARLY,
    environmentKeys: [],
    impactIfDown: 'Domeniul poate expira si site-ul nu mai este accesibil.',
    isRequiredForLaunch: true,
  },
  {
    name: 'DNS Provider',
    type: PlatformServiceType.DNS,
    providerName: 'Unknown',
    purpose: 'DNS pentru domeniu.',
    criticality: PlatformServiceCriticality.CRITICAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: [],
    impactIfDown: 'Site-ul/API-ul pot deveni inaccesibile prin domeniu.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Email Provider',
    type: PlatformServiceType.EMAIL,
    providerName: 'Resend/SMTP/SendGrid/Unknown',
    purpose: 'Invitatii, resetare parola, notificari email.',
    criticality: PlatformServiceCriticality.IMPORTANT,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: ['EMAIL_PROVIDER', 'EMAIL_FROM_ADDRESS', 'RESEND_API_KEY', 'SMTP_HOST'],
    impactIfDown: 'Emailurile reale nu se trimit. In-app poate functiona.',
    isRequiredForLaunch: false,
  },
  {
    name: 'SMS Provider',
    type: PlatformServiceType.SMS,
    providerName: 'Twilio/Custom/Unknown',
    purpose: 'SMS pentru notificari critice, daca va fi activat.',
    criticality: PlatformServiceCriticality.OPTIONAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: ['SMS_PROVIDER', 'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN'],
    impactIfDown: 'SMS-urile nu se trimit.',
    isRequiredForLaunch: false,
  },
  {
    name: 'Monitoring/Error Tracking',
    type: PlatformServiceType.MONITORING,
    providerName: 'Internal/Sentry/Unknown',
    purpose: 'Monitorizare erori si health.',
    criticality: PlatformServiceCriticality.IMPORTANT,
    status: PlatformServiceStatus.ACTIVE,
    billingCycle: PlatformServiceBillingCycle.FREE,
    environmentKeys: ['SENTRY_DSN'],
    impactIfDown: 'Erorile pot fi mai greu de detectat.',
    isRequiredForLaunch: true,
  },
  {
    name: 'Payment Provider',
    type: PlatformServiceType.PAYMENT_PROVIDER,
    providerName: 'BPay/Manual Test/Unknown',
    purpose: 'Plati online viitoare.',
    criticality: PlatformServiceCriticality.OPTIONAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: ['BPAY_ENABLED', 'BPAY_MERCHANT_ID', 'BPAY_API_KEY'],
    impactIfDown: 'Platile online nu functioneaza, dar platile manuale pot continua.',
    isRequiredForLaunch: false,
  },
  {
    name: 'Design Tool',
    type: PlatformServiceType.DESIGN_TOOL,
    providerName: 'Figma/Penpot/Unknown',
    purpose: 'Design UI/UX, prototipuri.',
    criticality: PlatformServiceCriticality.OPTIONAL,
    status: PlatformServiceStatus.UNKNOWN,
    billingCycle: PlatformServiceBillingCycle.UNKNOWN,
    environmentKeys: [],
    impactIfDown: 'Designul evolueaza mai greu, platforma live nu este oprita.',
    isRequiredForLaunch: false,
  },
] as const;
