import { DataRetentionAction, DataRetentionEntityType } from '@prisma/client';

export type RetentionPolicySeed = {
  entityType: DataRetentionEntityType;
  title: string;
  description: string;
  retentionAction: DataRetentionAction;
  defaultRetentionDays?: number;
  archiveAllowed: boolean;
  restoreAllowed: boolean;
  hardDeleteAllowed: boolean;
  anonymizationAllowed?: boolean;
  requiresSuperadminApproval?: boolean;
  legalHoldSupported?: boolean;
};

export const RETENTION_POLICY_SEEDS: RetentionPolicySeed[] = [
  {
    entityType: DataRetentionEntityType.INTERNAL_INVOICE,
    title: 'Facturi interne',
    description: 'Facturile interne sunt păstrate pentru istoric financiar și nu pot fi șterse definitiv.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.INTERNAL_INVOICE_LINE,
    title: 'Linii facturi interne',
    description: 'Liniile de factură sunt păstrate împreună cu factura finală.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.PAYMENT,
    title: 'Plăți',
    description: 'Plățile se păstrează pentru reconciliere. Corecțiile se fac prin anulare sau note, nu prin delete.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.AUDIT_LOG,
    title: 'Audit log',
    description: 'Audit log-ul este read-only și păstrat pentru trasabilitate.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.BILLING_RUN,
    title: 'Rulări facturare',
    description: 'Rulările de facturare și drafturile blocate/finale sunt păstrate pentru istoric.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.INVOICE_DRAFT,
    title: 'Drafturi facturi',
    description: 'Drafturile blocate sau finalizate nu se șterg definitiv.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.METER_READING,
    title: 'Indici contoare',
    description: 'Indicii aprobați se păstrează pentru istoricul consumului.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.SAAS_INVOICE,
    title: 'Facturi SaaS',
    description: 'Facturile SaaS se păstrează pentru istoricul abonamentelor Espace.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.SAAS_SUBSCRIPTION,
    title: 'Abonamente SaaS',
    description: 'Abonamentele se păstrează pentru audit comercial și operațional.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.SUPPORT_SESSION,
    title: 'Sesiuni support',
    description: 'Sesiunile de suport sunt păstrate pentru trasabilitatea accesului Superadmin.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.AUTH_SECURITY_EVENT,
    title: 'Evenimente securitate',
    description: 'Evenimentele de securitate sunt păstrate pentru investigații și audit.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.APARTMENT,
    title: 'Apartamente',
    description: 'Apartamentele inactive pot fi arhivate logic fără a șterge istoricul financiar.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.RESIDENT,
    title: 'Locatari',
    description: 'Locatarii inactivi pot fi arhivați. Anonymizarea necesită aprobare separată.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
    anonymizationAllowed: true,
    requiresSuperadminApproval: true,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.METER,
    title: 'Contoare',
    description: 'Contoarele înlocuite sau inactive pot fi arhivate, iar indicii rămân păstrați.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.ANNOUNCEMENT,
    title: 'Anunțuri',
    description: 'Anunțurile vechi pot fi arhivate și restaurate.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    defaultRetentionDays: 1095,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.REQUEST,
    title: 'Solicitări',
    description: 'Solicitările rezolvate sau închise pot fi arhivate fără ștergerea comentariilor.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.NOTIFICATION,
    title: 'Notificări',
    description: 'Notificările pot fi ascunse din view-ul utilizatorului, dar hard delete rămâne blocat.',
    retentionAction: DataRetentionAction.SOFT_DELETE_ALLOWED,
    defaultRetentionDays: 365,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.IMPORT_JOB,
    title: 'Import jobs',
    description: 'Importurile vechi pot fi arhivate, păstrând istoricul operațional.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.EXPORT_LOG,
    title: 'Export logs',
    description: 'Logurile de export sunt păstrate pentru trasabilitate.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.STAFF_INVITATION,
    title: 'Invitații staff',
    description: 'Invitațiile expirate pot fi arhivate logic.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.RESIDENT_INVITATION,
    title: 'Invitații locatari',
    description: 'Invitațiile expirate pot fi arhivate logic.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.STAFF_MEMBERSHIP,
    title: 'Staff memberships',
    description: 'Accesul staff se revocă/arhivează, nu se șterge definitiv.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.CUSTOMER_ONBOARDING_REQUEST,
    title: 'Cereri clienți',
    description: 'Cererile închise sau spam pot fi arhivate pentru curățarea listelor operaționale.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.LEGAL_DOCUMENT,
    title: 'Documente legale',
    description: 'Documentele legale și versiunile lor sunt păstrate pentru istoric.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
  {
    entityType: DataRetentionEntityType.HELP_ARTICLE,
    title: 'Articole help',
    description: 'Articolele help pot fi arhivate din listele publicate.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: true,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.SYSTEM_ERROR_EVENT,
    title: 'System error events',
    description: 'Evenimentele de eroare sunt păstrate pentru analiză operațională.',
    retentionAction: DataRetentionAction.ARCHIVE_ALLOWED,
    archiveAllowed: true,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.PLATFORM_SERVICE,
    title: 'Servicii platformă',
    description: 'Serviciile critice și istoricul lor se păstrează pentru go-live și operațiuni.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.BACKUP_CHECK,
    title: 'Backup checks',
    description: 'Verificările de backup se păstrează pentru pregătirea recovery.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
  },
  {
    entityType: DataRetentionEntityType.PRODUCTION_INCIDENT,
    title: 'Incidente producție',
    description: 'Incidentele se păstrează pentru postmortem și audit operațional.',
    retentionAction: DataRetentionAction.KEEP_FOREVER,
    archiveAllowed: false,
    restoreAllowed: false,
    hardDeleteAllowed: false,
    legalHoldSupported: true,
  },
];
